### ISSUE TITLE
please create a new tag

### ISSUE THREAD

**Issue by aviau** [YukiWorkshop/libevdevPlus#4]
Hello,

I am currently packaging ydotool for Debian.

However, it requires a newer version of libevdevPlus than v0.1.0, which is the last tag.

One of the reason is that it usesTable_ModifierKeys.

Would you be willing to create a new tag for libevdevPlus?

Thank you in advance!

**Comment by ReimuNotMoe** [comment]
Done.

https://github.com/YukiWorkshop/libevdevPlus/tree/v0.1.1

Thanks for the packaging!

**Comment by aviau** [comment]
Thanks!
